# image: python:latest
image: python:3.4
services:
  - mysql:latest
stages:
  - prepare

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  MYSQL_DATABASE: "pub_download"
  MYSQL_ROOT_PASSWORD: "pub_pass"

cache:
  paths:
    - .cache/pip
    - venv/

install:
  stage: prepare
  script:
  - install_dependencies
  - make_documentation

# test:
#   stage: prepare
#   script:
#   - install_dependencies
#   - pip install tox flake8  # you can also use tox
#   - tox -e py34,flake8

# pages:
#   stage: prepare
#   image: mysql
#   script:
#   - make_documentation
#   only:
#   - master


.auto_devops: &auto_devops |
  function install_dependencies() {
    python -V               # Print out python version for debugging
    pip install virtualenv
    virtualenv venv --python=python3
    source venv/bin/activate
    pip install -r requeriments.txt
  }
  function make_documentation() {
    source venv/bin/activate
    pip install sphinx sphinx-rtd-theme
    cd docs ; make html
    mv build/html/ ../public/
  }
before_script:
  - *auto_devops

mysql_build:
  stage: prepare
  image: mysql
  script:
  - mysql --version
  - echo "SELECT 'OK';" | mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" --host=mysql "${MYSQL_DATABASE}"


