# Generated by Django 2.0.7 on 2018-07-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='google_service',
            name='service',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='google_service',
            name='version',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='google_service',
            name='view_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
