# Generated by Django 2.0.7 on 2018-07-18 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0004_publication_stats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stats',
            options={'ordering': ['google_service', 'publication', 'period'], 'verbose_name': 'STATS', 'verbose_name_plural': 'STATS'},
        ),
        migrations.AlterUniqueTogether(
            name='stats',
            unique_together={('google_service', 'period', 'publication')},
        ),
    ]
