# Generated by Django 2.0.7 on 2018-07-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0005_auto_20180718_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
