# Generated by Django 2.0.7 on 2018-07-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0006_auto_20180718_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=600),
        ),
    ]
