# Generated by Django 2.0.7 on 2018-07-18 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0007_auto_20180718_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dspace', models.PositiveSmallIntegerField(default=0, help_text='ID Dspace', unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stats',
            name='google_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gug.Google_service'),
        ),
        migrations.AddField(
            model_name='publication',
            name='id_dspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gug.Dspace'),
        ),
    ]
