# Generated by Django 2.0.7 on 2018-07-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0008_auto_20180718_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='turl',
            new_name='tfile',
        ),
    ]
