# Generated by Django 2.0.7 on 2018-07-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0009_auto_20180718_1433'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publication',
            unique_together={('id_dspace', 'tfile')},
        ),
    ]
