# Generated by Django 2.0.7 on 2018-07-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0010_auto_20180718_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['id_dspace', 'tfile']},
        ),
        migrations.AddField(
            model_name='dspace',
            name='title',
            field=models.CharField(default='', max_length=600),
        ),
    ]
