# Generated by Django 2.0.7 on 2018-07-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0011_auto_20180718_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='title',
        ),
    ]
