# Generated by Django 2.0.7 on 2018-07-18 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0012_remove_publication_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='id_dspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gug.Dspace'),
        ),
    ]
