# Generated by Django 2.0.7 on 2018-07-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0014_auto_20180718_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dspace',
            name='id_dspace',
            field=models.PositiveIntegerField(default=0, help_text='ID Dspace', unique=True),
        ),
    ]
