# Generated by Django 2.0.7 on 2018-07-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0015_auto_20180718_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
