# Generated by Django 2.0.7 on 2018-07-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0017_auto_20180718_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='google_service',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
