# Generated by Django 2.0.7 on 2018-07-18 20:37

from django.db import migrations, models
import gug.models


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0018_google_service_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='google_service',
            name='report',
            field=models.TextField(blank=True, default='{}', null=True, validators=[gug.models.validate_json]),
        ),
    ]
