# Generated by Django 2.0.7 on 2018-07-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0019_google_service_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='google_service',
            name='discovery',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
