# Generated by Django 2.0.7 on 2018-07-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0020_auto_20180718_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
