# Generated by Django 2.0.7 on 2018-07-19 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0021_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='google_service',
            name='service_t',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gug.Service_type'),
        ),
    ]
