# Generated by Django 2.0.7 on 2018-07-19 13:51

from django.db import migrations, models
import gug.models


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0024_auto_20180719_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='google_service',
            name='report',
            field=models.TextField(default='{}', help_text='Transformed variables are view_id, start_date and end_date.', validators=[gug.models.validate_json]),
        ),
        migrations.AlterField(
            model_name='google_service',
            name='view_id',
            field=models.CharField(default='', help_text='In Google Analytics is View Id, in Google Webmaster is protocol+domain', max_length=30),
        ),
    ]
