# Generated by Django 2.0.7 on 2018-07-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0030_dspace_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dspace',
            name='post_title',
        ),
        migrations.AddField(
            model_name='dspace',
            name='post_title1',
            field=models.CharField(default='', max_length=300),
        ),
    ]
