# Generated by Django 2.0.7 on 2018-07-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0031_auto_20180726_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='dspace',
            name='post_title2',
            field=models.CharField(default='', max_length=200),
        ),
    ]
