# Generated by Django 2.0.7 on 2018-08-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0032_dspace_post_title2'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stats',
            index=models.Index(fields=['id_dspace', 'google_service', 'period'], name='stats_iddspace_idx'),
        ),
    ]
