# Generated by Django 2.0.7 on 2018-08-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0033_auto_20180804_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='google_service',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Hidden in application'),
        ),
    ]
