# Generated by Django 2.0.7 on 2018-08-07 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0034_google_service_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='google_service',
            name='hidden',
        ),
    ]
