# Generated by Django 2.0.7 on 2018-11-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0035_remove_google_service_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Service group',
                'verbose_name_plural': 'Service groups',
            },
        ),
    ]
