# Generated by Django 2.0.7 on 2018-11-05 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0036_service_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='google_service',
            name='group',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='gug.Service_group'),
        ),
    ]
