# Generated by Django 2.0.7 on 2018-11-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0037_google_service_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='google_service',
            name='view_id',
            field=models.CharField(default='', help_text='In Google Analytics is View Id, in Google Webmaster is protocol+domain', max_length=60),
        ),
    ]
