# Generated by Django 2.0.7 on 2019-01-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0038_auto_20181106_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
