# Generated by Django 2.0.7 on 2019-01-02 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0042_auto_20190102_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workarea',
            options={'ordering': ['name']},
        ),
    ]
