# Generated by Django 2.0.7 on 2019-01-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0044_period_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='google_service',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
    ]
