# Generated by Django 2.0.7 on 2019-01-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0045_google_service_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_type',
            name='max_month_before',
            field=models.PositiveSmallIntegerField(default=0, help_text='Month service deliver stats'),
        ),
    ]
