# Generated by Django 2.0.7 on 2019-03-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0046_service_type_max_month_before'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service_group',
            options={'ordering': ['order'], 'verbose_name': 'Service group', 'verbose_name_plural': 'Service groups'},
        ),
        migrations.AddField(
            model_name='service_group',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
