# Generated by Django 2.0.7 on 2019-06-17 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gug', '0047_auto_20190308_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('extension_chars', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='id_extension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gug.Extension'),
        ),
    ]
