# Generated by Django 2.0.7 on 2018-07-17 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(help_text='Unique reference ID for this domain', max_length=100, unique=True)),
                ('name', models.CharField(blank=True, help_text='Short descriptive name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(help_text='Unique reference ID for this metric within the domain', max_length=100)),
                ('name', models.CharField(blank=True, help_text='Short descriptive name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='google_analytics.Domain')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='metric',
            unique_together={('domain', 'ref')},
        ),
    ]
