# Generated by Django 2.0.7 on 2018-07-17 16:48

from django.db import migrations, models
import google_analytics.models


class Migration(migrations.Migration):

    dependencies = [
        ('google_analytics', '0002_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Google_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scope', models.CharField(max_length=200)),
                ('discovery', models.CharField(max_length=200)),
                ('secret_json', models.TextField(blank=True, default='{}', null=True, validators=[google_analytics.models.validate_json])),
            ],
        ),
    ]
